orb_slam2_mono:
  ros__parameters:

    publish_pointcloud: true
    publish_pose: true
    localize_only: true
    reset_map: false

    # static parameters
    load_map: true
    map_file: /home/iggy/ros/eloquent/src/orb_slam_2_ros/ros/map/test1.bin

    pointcloud_frame_id: map
    camera_frame_id: odom
    min_num_kf_in_map: 5

    #ORB parameters
    ORBextractor/nFeatures: 3000 #2000
    ORBextractor/scaleFactor: 1.2
    ORBextractor/nLevels: 8
    ORBextractor/iniThFAST: 15 #20
    ORBextractor/minThFAST: 4 #7

    #Camera Parameters
    #Camera frames per second
    camera_fps: 30
    #Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale) 
    camera_rgb_encoding: true
